remove vim-go

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,129 +1,58 @@
-FROM ubuntu
+FROM golang:latest
 
+# Set shell to fail on error
 SHELL ["/bin/bash", "-euo", "pipefail", "-c"]
 
-# Create system wide environment as root
-
-## Supports linux/amd64 or linux/arm64
-ARG TARGETPLATFORM
-
-## Ensure installation does not prompt for input
-ARG DEBIAN_FRONTEND=noninteractive
-
-## Install basic tools
-RUN apt-get -yq update && \
-    apt-get -yq upgrade && \
-    apt-get -yq install \
-    git \
-    vim \
-    tmux \
-    curl \
-    wget \
-    build-essential \
-    cmake \
-    gcc \
-    shellcheck \
-    unzip \
-    tree \
-    software-properties-common \
-    jq \
-    gettext-base \
-    uuid-runtime \
-    postgresql-client \
-    sqlite3 \
-    pandoc \
-    texlive \
-    texlive-latex-extra \
-    wkhtmltopdf \
-    htop
-
-## Install latest vim
-RUN add-apt-repository ppa:jonathonf/vim && \
-	apt-get update && \
-	apt-get -yq install vim
-
-## Install latest python
-RUN add-apt-repository ppa:deadsnakes/ppa -y && \
-    apt-get update && \
-    apt-get -yq install python3 python3-dev python3-venv python3-pip && \
-    ln -s /usr/bin/python3 /usr/bin/python
-
-## Install latest go
-RUN GO_VERSION="$(git ls-remote https://github.com/golang/go | grep -oE "refs/tags/go[0-9]+\.[0-9]+(\.[0-9])?$" | sed 's|refs/tags/go||g' | sort --version-sort | tail -n 1)" && \
-    ARCH=$(basename "${TARGETPLATFORM}") && \
-    curl -fsSL "https://dl.google.com/go/go${GO_VERSION}.linux-${ARCH}.tar.gz" | tar -xz -C /usr/local
-
-## Install latest docker
-RUN curl -fsSL https://get.docker.com | bash
-
-## Install latest doctl
-RUN DOCTL_VERSION="$(git ls-remote https://github.com/digitalocean/doctl | grep refs/tags | grep -oE "[0-9]+\.[0-9]+\.[0-9]+$" | sort --version-sort | tail -n 1)" && \
-    ARCH=$(basename "${TARGETPLATFORM}") && \
-    curl -fsSL "https://github.com/digitalocean/doctl/releases/download/v${DOCTL_VERSION}/doctl-${DOCTL_VERSION}-linux-${ARCH}.tar.gz" | tar -xz -C /usr/local/bin && \
-    chmod +x /usr/local/bin/doctl
-
-# Customize environment for nonroot user
+# Create non-root user and add to sudoers and docker group
 ARG USERNAME=nonroot
-ENV HOME=/home/nonroot
 ARG USER_UID=1000
 ARG USER_GID=1000
 RUN groupadd --gid "${USER_GID}" "${USERNAME}" && \
     useradd --uid "${USER_UID}" --gid "${USER_GID}" --create-home "${USERNAME}" && \
     apt-get update && \
-    apt-get -yq install sudo && \
-    echo "${USERNAME}" ALL=\(root\) NOPASSWD:ALL > "/etc/sudoers.d/${USERNAME}" && \
-    chmod 0440 "/etc/sudoers.d/${USERNAME}" && \
+    apt-get install -yq sudo && \
+    echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
+    curl -fsSL https://get.docker.com | sh && \
+    groupadd docker || true && \
     usermod -aG docker "${USERNAME}"
+
+# Install necessary packages
+RUN apt-get update && \
+    apt-get install -yq --no-install-recommends \
+    git vim tmux curl wget build-essential cmake gcc \
+    shellcheck unzip tree jq postgresql-client sqlite3 htop \
+    python3 python3-dev python3-venv python3-pip \
+    nodejs npm && \
+    ln -s /usr/bin/python3 /usr/bin/python && \
+    apt-get clean && sudo rm -rf /var/lib/apt/lists/* && \
+    rm -rf /var/lib/apt/lists/*
+
+# Set environment variables
+ENV HOME="/home/${USERNAME}"
+
+# Switch to non-root user
 USER "${USERNAME}:${USERNAME}"
+WORKDIR "${HOME}"
 
-## Delete default configs
-RUN rm "${HOME}/.profile" "${HOME}/.bashrc" && \
-    touch "${HOME}/.bashrc"
-
-## Install latest node
-RUN curl -fsSL "https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh" | PROFILE="${HOME}/.bashrc" bash && \
-    source "${HOME}/.bashrc" && \
-    nvm install node && \
-    nvm use node
-
-## Install vim plugins
-RUN mkdir -p "${HOME}/.vim"
-COPY --chown="${USERNAME}:${USERNAME}" .vimrc "${HOME}/.vimrc"
-COPY --chown="${USERNAME}:${USERNAME}" coc-settings.json "${HOME}/.vim/coc-settings.json"
-RUN source "${HOME}/.bashrc" && \
-curl -fLo "${HOME}/.vim/autoload/plug.vim" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && \
-    vim +'PlugInstall --sync' +qa
-
-# Install go packages
-ENV GOROOT="/usr/local/go"
-ENV GOPATH="${HOME}/go"
-ENV PATH="${GOROOT}/bin:${GOPATH}/bin:${PATH}"
+# Install go tools
 RUN go install golang.org/x/tools/gopls@latest && \
     go install github.com/go-delve/delve/cmd/dlv@latest
 
-# Install python libraries
-ENV PATH="${HOME}/.local/bin:${PATH}"
-RUN pip3 install black pandas numpy matplotlib jupyterlab
+# Setup vim configurations
+COPY --chown=${USERNAME}:${USERNAME} .vimrc ${HOME}/.vimrc
+COPY --chown="${USERNAME}:${USERNAME}" coc-settings.json "${HOME}/.vim/coc-settings.json"
 
-## Customize tmux
-RUN echo "set-option -g default-command /bin/bash" > "${HOME}/.tmux.conf" && \
-    echo "set-option -g mouse on" >> "${HOME}/.tmux.conf"
+# Install vim plugins
+RUN curl -fLo "${HOME}/.vim/autoload/plug.vim" --create-dirs \
+    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && \
+    vim +'PlugInstall --sync' +qa
 
-## Customize bashrc
-RUN echo "export TERM=xterm-color" >> "${HOME}/.bashrc" && \
-    sudo cat /root/.bashrc >> "${HOME}/.bashrc" && \
-    echo "set -o vi" >> "${HOME}/.bashrc" && \
-    echo "alias tmux='tmux -u'" >> "${HOME}/.bashrc" && \
-    echo "export PATH=${PATH}" >> "${HOME}/.bashrc" && \
-    echo "nvm use node > /dev/null 2>&1" >> "${HOME}/.bashrc"
+# Configure colored shell prompt
+RUN echo 'PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "' >> "${HOME}/.bashrc"
 
-## Customize .profile
-RUN sudo cat /root/.profile >> "${HOME}/.profile"
+# Configure tmux to source .bashrc for interactive shells
+RUN echo 'set-option -g default-command "bash -i"' >> "${HOME}/.tmux.conf"
 
-## Cleanup
-RUN sudo apt-get clean && \
-    sudo rm -rf /var/lib/apt/lists/*
-
-# Mimic VSCode's workspace
+# Setup workspace
 RUN mkdir -p "${HOME}/workspaces/dev-container"
 WORKDIR "${HOME}/workspaces/dev-container"
